/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnoCSSIconButton: typeof import('./../src/components/Icon/UnoCSSIconButton.vue')['default']
    UnoCSSNavLink: typeof import('./../src/components/link/UnoCSSNavLink.vue')['default']
    UnoImg: typeof import('./../src/components/Image/UnoImg.vue')['default']
    UnoZestyTestiCarousel: typeof import('./../src/components/Carousel/UnoZestyTestiCarousel.vue')['default']
  }
}
